import{a as v,S,i as n}from"./assets/vendor-C3lJ7lpQ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const q="51685894-420173baf9b205d39b44ad1de",P="https://pixabay.com/api/",B=15;async function f(o,t=1){const i={q:o,key:q,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:B};return(await v.get(P,{params:i})).data}const m=document.querySelector(".gallery"),p=document.querySelector(".loader"),g=document.querySelector(".load-more"),M=new S(".gallery a",{captionData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:i,largeImageURL:a,tags:e,likes:r,views:c,comments:b,downloads:w})=>`<li class="gallery-item">
    <a href="${a}">
    <img src="${i}" alt="${e}" />
    </a>
    <div class="info">
    <p>Likes<br>${r}</p>
    <p>Views<br>${c}</p>
    <p>Comments<br>${b}</p>
    <p>Downloads<br>${w}</p>
    </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",t),M.refresh()}function $(){m.innerHTML=""}function L(){p.classList.remove("hidden")}function h(){p.classList.add("hidden")}function R(){g.classList.remove("hidden")}function u(){g.classList.add("hidden")}const E=document.querySelector(".load-more"),O=document.querySelector(".gallery");let l="",s=1,d=0;const x=document.querySelector(".form");x.addEventListener("submit",async o=>{if(o.preventDefault(),l=o.target.elements["search-text"].value.trim(),s=1,!l){n.warning({title:"Attention",message:"Please enter a search query!",position:"topRight"});return}$(),L(),u();try{const t=await f(l,s),{totalHits:i}=t;if(t.hits.length===0){n.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(t.hits),d=Math.ceil(i/15),d===1&&(u(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),s<d&&R()}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{h()}});E.addEventListener("click",async o=>{s+=1,u(),L();try{const t=await f(l,s),{hits:i}=t;y(i),C(),s===d&&(u(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),h())}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{h()}});function C(){const o=O.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
