import{a as S,S as q,i as n}from"./assets/vendor-C3lJ7lpQ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const P="51685894-420173baf9b205d39b44ad1de",B="https://pixabay.com/api/",M=15;async function h(o,t=1){const i={q:o,key:P,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:M};return(await S.get(B,{params:i})).data}const m=document.querySelector(".gallery"),p=document.querySelector(".loader"),g=document.querySelector(".load-more"),$=new q(".gallery a",{captionData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:i,largeImageURL:a,tags:e,likes:r,views:c,comments:w,downloads:v})=>`<li class="gallery-item">
    <a href="${a}">
    <img src="${i}" alt="${e}" />
    </a>
    <div class="info">
    <p>Likes<br>${r}</p>
    <p>Views<br>${c}</p>
    <p>Comments<br>${w}</p>
    <p>Downloads<br>${v}</p>
    </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",t),$.refresh()}function R(){m.innerHTML=""}function L(){p.classList.remove("hidden")}function f(){p.classList.add("hidden")}function b(){g.classList.remove("hidden")}function u(){g.classList.add("hidden")}const E=document.querySelector(".load-more"),O=document.querySelector(".gallery");let d="",s=1,l=0;const x=document.querySelector(".form");x.addEventListener("submit",async o=>{if(o.preventDefault(),d=o.target.elements["search-text"].value.trim(),s=1,!d){n.warning({title:"Attention",message:"Please enter a search query!",position:"topRight"});return}R(),L(),u();try{const t=await h(d,s),{totalHits:i}=t;if(t.hits.length===0){n.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(t.hits),l=Math.ceil(i/15),l===1&&(u(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),l>1&&b()}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{f()}});E.addEventListener("click",async o=>{s+=1,u(),L();try{const t=await h(d,s),{hits:i}=t;y(i),C(),s===l&&(u(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),f()),s<l&&b()}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{f()}});function C(){const o=O.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
