import{a as w,S as v,i as n}from"./assets/vendor-C3lJ7lpQ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const S="51685894-420173baf9b205d39b44ad1de",q="https://pixabay.com/api/",P=15;async function f(o,t=1){const i={q:o,key:S,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:P};return(await w.get(q,{params:i})).data}const p=document.querySelector(".loader"),m=document.querySelector(".load-more"),B=new v(".gallery a",{captionData:"alt",captionDelay:250});function g(o){const t=o.map(({webformatURL:i,largeImageURL:a,tags:e,likes:r,views:l,comments:L,downloads:b})=>`<li class="gallery-item">
    <a href="${a}">
    <img src="${i}" alt="${e}" />
    </a>
    <div class="info">
    <p>Likes<br>${r}</p>
    <p>Views<br>${l}</p>
    <p>Comments<br>${L}</p>
    <p>Downloads<br>${b}</p>
    </div>
    </li>`).join("");galleryContainer.insertAdjacentHTML("beforeend",t),B.refresh()}function M(){galleryContainer.innerHTML=""}function y(){p.classList.remove("hidden")}function h(){p.classList.add("hidden")}function $(){m.classList.remove("hidden")}function u(){m.classList.add("hidden")}const R=document.querySelector(".load-more"),C=document.querySelector(".gallery");let c="",s=1,d=0;const E=document.querySelector(".form");E.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements["search-text"].value.trim(),s=1,!c){n.warning({title:"Attention",message:"Please enter a search query!",position:"topRight"});return}M(),y(),u();try{const t=await f(c,s),{totalHits:i}=t;if(t.hits.length===0){n.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(t.hits),d=Math.ceil(i/15),d===1&&(u(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),s<d&&$()}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{h()}});R.addEventListener("click",async o=>{s+=1,u(),y();try{const t=await f(c,s),{hits:i}=t;g(i),O(),s===d&&(u(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),h())}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{h()}});function O(){const o=C.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
